blank_issues_enabled: false
contact_links:
  - name: XLibre on openSUSE Linux Discussions
    url: https://github.com/X11Libre/packaging/discussions/categories/xlibre-on-opensuse
    about: Please ask and answer questions here.
